declare const classes: {
  readonly [key: string]: string;
  readonly "jsfaq-ssr-wrapper": string;
  readonly "jsfaq": string;
  readonly "jsfaq__header": string;
  readonly "jsfaq__title": string;
  readonly "jsfaq__intro": string;
  readonly "jsfaq__section__description": string;
  readonly "jsfaq-item__answer-content": string;
  readonly "jsfaq__controls": string;
  readonly "jsfaq__search": string;
  readonly "jsfaq__search-label": string;
  readonly "jsfaq__search-field": string;
  readonly "jsfaq__search-icon": string;
  readonly "jsfaq__search-input": string;
  readonly "jsfaq-tags": string;
  readonly "jsfaq-tags__label": string;
  readonly "jsfaq-tags__list": string;
  readonly "jsfaq-tag": string;
  readonly "jsfaq-tag__check": string;
  readonly "jsfaq-tag--active": string;
  readonly "jsfaq__toolbar": string;
  readonly "jsfaq__status": string;
  readonly "jsfaq__toolbar-actions": string;
  readonly "jsfaq-button": string;
  readonly "jsfaq__content": string;
  readonly "jsfaq__section": string;
  readonly "jsfaq__section__header": string;
  readonly "jsfaq__section__title": string;
  readonly "jsfaq__section__items": string;
  readonly "jsfaq-item": string;
  readonly "jsfaq-item--open": string;
  readonly "jsfaq-item__heading": string;
  readonly "jsfaq-item__label": string;
  readonly "jsfaq-item__toggle": string;
  readonly "jsfaq-item__question": string;
  readonly "jsfaq-item__icon": string;
  readonly "jsfaq-badge": string;
  readonly "jsfaq-item__answer": string;
  readonly "jsfaq-item__tags": string;
  readonly "jsfaq-item__tag": string;
  readonly "jsfaq-highlight": string;
};

export default classes;
