declare const classes: {
  readonly [key: string]: string;
  readonly "jsfaq-ssr-wrapper": string;
  readonly "jsfaq": string;
  readonly "jsfaq__header": string;
  readonly "jsfaq__title": string;
  readonly "jsfaq__intro": string;
  readonly "jsfaq__controls": string;
  readonly "jsfaq-search": string;
  readonly "jsfaq-search__field": string;
  readonly "jsfaq-search__actions": string;
  readonly "jsfaq-search__toggles": string;
  readonly "jsfaq-search__toggle": string;
  readonly "jsfaq-button": string;
  readonly "jsfaq-button--ghost": string;
  readonly "jsfaq-button--link": string;
  readonly "jsfaq-tags": string;
  readonly "jsfaq-tag": string;
  readonly "jsfaq-tag--active": string;
  readonly "jsfaq__content": string;
  readonly "jsfaq-section": string;
  readonly "jsfaq-section--standalone": string;
  readonly "jsfaq-section__header": string;
  readonly "jsfaq-section__title": string;
  readonly "jsfaq-section__description": string;
  readonly "jsfaq-section__items": string;
  readonly "jsfaq-item": string;
  readonly "jsfaq-item--open": string;
  readonly "jsfaq-item--collapsed": string;
  readonly "jsfaq-item__header": string;
  readonly "jsfaq-item__question": string;
  readonly "jsfaq-item__toggle": string;
  readonly "jsfaq-badge": string;
  readonly "jsfaq-item__actions": string;
  readonly "jsfaq-item__copy-feedback": string;
  readonly "jsfaq-item__copy-feedback--visible": string;
  readonly "jsfaq-item__answer": string;
  readonly "jsfaq-item__answer-content": string;
  readonly "jsfaq-item__tags": string;
  readonly "jsfaq-item__tag": string;
  readonly "jsfaq-empty": string;
  readonly "jsfaq-visually-hidden": string;
};

export default classes;
